# These are optional. Remove any you don't want.
# Customize the sponsorship links as needed.

# GitHub Sponsors (when enabled)
# custom: https://github.com/sponsors/soumyachk101

# Open Collective (if set up)
# open_collective: ensembyte

# Ko-fi (if set up)
# ko_fi: soumyachk101

# Liberapay (if set up)
# liberapay: soumyachk101
